### ISSUE TITLE
"RRULE:FREQ=YEARLY" is considered to be a monthly thing

### ISSUE THREAD

**Issue by tobixen** [roburio/caldav#28]
I'm the developer of the python caldav client library.  While testing the library towards calendar.robur.coop, I found that a yearly event was expanded into a monthly event.

The icalendar object (copied verbatim from the example section of the RFC) looks like this:

```icalendar
"BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
DTSTAMP:19970901T130000Z
DTSTART;VALUE=DATE:19971102
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
CLASS:CONFIDENTIAL
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
RRULE:FREQ=YEARLY
END:VEVENT
END:VCALENDAR
```

When doing a date search and asking the server to expand the icalendar, I get this in return:

```icalendar
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
RECURRENCE-ID;VALUE=DATE:20091102
DTSTART;VALUE=DATE:20091102
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
RECURRENCE-ID;VALUE=DATE:20091002
DTSTART;VALUE=DATE:20091002
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
RECURRENCE-ID;VALUE=DATE:20090902
DTSTART;VALUE=DATE:20090902
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
RECURRENCE-ID;VALUE=DATE:20090802
DTSTART;VALUE=DATE:20090802
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
CLASS:CONFIDENTIAL
DTSTAMP:19970901T130000Z
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
END:VEVENT
(...)
```

**Comment by tobixen** [comment]
This can be reproduced using the caldav library tests.

```bash
git clone git@github.com:python-caldav/caldav.git
cd caldav
git checkout bug-robur-28
echo 'from tests import compatibility_issues ; caldav_servers=[{"url": "https://calendar.robur.coop/principals/", "username": "test28", "password": "hunter2", "incompatibilities": compatibility_issues.robur}]' > tests/conf_private.py
nosetests3 --pdb tests.test_caldav:TestForServer_calendar_robur_coop.testRecurringDateSearch
```

(though unfortunately `teardown()` seems to be run before one is thrown into the debugger, causing the test calendar and event to disappear before it's possible to debug it.  I've heard nosetest is deprecated, I should probably investigate the alternatives).

**Comment by hannesm** [comment]
Thanks for your report (and the other issue). I'll look into that later in the month. Could you post the HTTP request you're doing, please? (I'm not entirely sure what your `date search` is doing at the HTTP level).

**Comment by tobixen** [comment]
Yes, let me fish that out ... the XML query looks like this:

```
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="20081101T160000Z" end="20081103T160000Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```

... and it's doing a REPORT towards https://calendar.robur.coop/calendars/pythoncaldav-test/

(I should eventually make some debug hook to get the full request with HTTP communication printed out and with the XML pretty formatted ... but not now, it's past bedtime) :-)

The event and calendar is recreated and destroyed every time the test is run, but I can push it to another calendar if you want to investigate from there.

**Comment by hannesm** [comment]
Thanks again for your report. I added a test and fix to the icalendar library. I'll reply back here once the calendar.robur.coop runs with the up-to-date version, so you can check that it is indeed fixed.

**Comment by hannesm** [comment]
Finally, the live test server at https://calendar.robur.coop is using the fixed icalendar library. Would you mind to test whether the issue you reported here is gone? Thanks a lot!

**Comment by tobixen** [comment]
Tests passes.  Yay! :-)
