### ISSUE TITLE
https key permissions?

### ISSUE THREAD

**Issue by jedahan** [roburio/caldav#4]
I generated the keys with
```
opam install certify
selfsign -c server.pem -k server.key "calendar.example.com"
mv server.pem server.key caldav/mirage/tls/
```

Did chmod 644 for the generated files. And ran from the mirage subdirectory.

```
~/caldav/mirage/ ./main.native --data=/home/micro/volumes/caldav --admin-password="somepassword" --host="calendar.example.com" --http=3080 --https=3443
2019-01-07 20:31:02 +00:00: INF [tcpip-stack-socket] Manager: connect
2019-01-07 20:31:02 +00:00: INF [tcpip-stack-socket] Manager: configuring
2019-01-07 20:31:02 +00:00: INF [http.server] redirecting on 3080/HTTP to 3443/HTTPS
2019-01-07 20:31:02 +00:00: ERR [application] main: (Failure
  "Could not find server.pem and server.key in the <working directory>/tls.")
Raised at file "map.ml", line 131, characters 10-25
Called from file "src/unix/lwt_engine.ml", line 302, characters 8-36
```

but it cannot see the keys. I also copied them to `/home/micro/volumes/caldav/tls` but got the same error.

**Comment by hannesm** [comment]
seems like we lack some documentation: after you copy the certificate and private key to the caldav/mirage/tls subdirectory, you have to run make again in the caldav/mirage directory -- this will embed the certificate and key in the resulting binary (a unikernel configured for unix atm).

**Comment by jedahan** [comment]
ahh that makes total sense :)
