### ISSUE TITLE
graphql-cohttp version does not exist in opam

### ISSUE THREAD

**Issue by reynir** [roburio/caldav#5]
https://github.com/roburio/caldav/blob/7978be8a56dd5ca58a18c967d4987824884eba28/mirage/config.ml#L121
This outputs a restriction on graphql-cohttp < 0.8.0, but the earliest version of that package in opam is exactly 0.8.0.

**Comment by hannesm** [comment]
sorry for this, right now there's a branch named `future` in this repository, which requires the opam repository `git+https://github.com/roburio/git-ssh-dns-mirage3-repo.git` and leads to a caldav unikernel which uses a git remote (https/git/git+ssh) for persisting data.

**Comment by dysinger** [comment]
I had the same issue. When I tweaked the max to 0.8.1 it then complained that irmin-graphql doesn't exist.

**Comment by dysinger** [comment]
I have pushed a dockerfile which demonstrates these issues. Maybe it would be useful to include. I'll make a P/R.

**Comment by dysinger** [comment]
On the `future` branch my dockerfile demonstrates that, on a fresh system, the build fails while trying to find `irmin-graphql`

```
Step 11/14 : RUN opam depext caldav mirage-unikernel-caldav-unix
 ---> Running in b201b02abc94
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for caldav & mirage-unikernel-caldav-unix: The following dependencies couldn't be met:
          - mirage-unikernel-caldav-unix -> irmin-mirage-git
              unknown package


Command failed: opam list --readonly --external  --resolve=caldav,mirage-unikernel-caldav-unix returned 20
The command '/bin/sh -c opam depext caldav mirage-unikernel-caldav-unix' returned a non-zero code: 20
```

**Comment by hannesm** [comment]
thanks for your work on this, sorry for getting back only now. There is a branch named `future` with more up-to-date build instructions (using a custom opam remote repository) -- https://github.com/roburio/caldav/tree/future -- if you could give that a spin, please let us know whether there's something broken with it. in the meantime, we should get the futture branch merged rather sooner than later.

**Comment by dysinger** [comment]
Ah. I need to read more. BRB

**Comment by hannesm** [comment]
@dysinger I opened #9 with these changes, and at least some days ago travis successfully built that unikernel.

**Comment by dysinger** [comment]
I rebased the dockrefile on `future` and added the opam repo. It still fails to find all the dependencies. I'll keep trying it. Consider me your test rabbit.

**Comment by hannesm** [comment]
would you mind to elaborate which dependencies are missing?

**Comment by dysinger** [comment]
The dockrefile on my P/R `future` branch shows:

```
Step 12/15 : RUN opam depext caldav mirage-unikernel-caldav-unix
 ---> Running in ba8c5f38f14e
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for caldav & mirage-unikernel-caldav-unix: The following dependencies couldn't be met:
          - mirage-unikernel-caldav-unix -> irmin-mirage-git
              unknown package


Command failed: opam list --readonly --external  --resolve=caldav,mirage-unikernel-caldav-unix returned 20
```

**Comment by hannesm** [comment]
hmm, but https://github.com/roburio/git-ssh-dns-mirage3-repo/tree/master/packages/irmin-mirage-git.2.0.0%7Edev shows a package with such a name...

**Comment by dysinger** [comment]
I started out trying to build this project with Nix. I'll have that P/R also once I can get past "it builds with docker on debian"

**Comment by hannesm** [comment]
I unfortunately neither have a computer which is able to execute docker, neither knowledge about dockerfiles in general. To me it looks like somehow the `opam repo add ..` is not picked up. What I tested were the installation instructions I wrote in the README in a fresh opam switch.

**Comment by dysinger** [comment]
I see an error on my part. hold tight. brb

**Comment by dysinger** [comment]
Switch from 4.06.1 to 4.07.x I get further but then:
```
#=== ERROR while compiling tls.0.10.2 =========================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/tls.0.10.2
# command              ~/.opam/4.07/bin/ocaml pkg/pkg.ml build --pinned false --tests false --with-lwt true --with-mirage true
# exit-code            1
# env-file             ~/.opam/log/tls-7-580b5c.env
# output-file          ~/.opam/log/tls-7-580b5c.out
### output ###
# [...]
# Error: Unbound value Nocrypto.Hash.hash_of_sexp
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'lib/tls.cmi' 'lib/tls.a' 'lib/tls.cmxs' 'lib/tls.cmxa'
#      'lib/tls.cma' 'lib/tls.cmx' 'lwt/tls-lwt.a' 'lwt/tls-lwt.cmxs'
#      'lwt/tls-lwt.cmxa' 'lwt/tls-lwt.cma' 'lwt/x509_lwt.cmx'
#      'lwt/x509_lwt.cmi' 'lwt/x509_lwt.mli' 'lwt/tls_lwt.cmx'
#      'lwt/tls_lwt.cmi' 'lwt/tls_lwt.mli' 'mirage/tls-mirage.a'
#      'mirage/tls-mirage.cmxs' 'mirage/tls-mirage.cmxa'
#      'mirage/tls-mirage.cma' 'mirage/tls_mirage.cmx' 'mirage/tls_mirage.cmi'
#      'mirage/tls_mirage.mli']: exited with 10
```

**Comment by hannesm** [comment]
the actual issue is that an old tls is picked up here :/ -- I just (3 minutes ago) pushed some commits to the opam repository overlay (and a branch of x509), would you mind to retry?

**Comment by hannesm** [comment]
oops, and i needed to update conduit as well... pushed my changes..

**Comment by hannesm** [comment]
so, travis now completed successfully (see https://api.travis-ci.org/v3/job/562210515/log.txt) -- if you still encounter an issue, please ping here, and I'll put some more lower bounds into the unikernel itself... thanks for testing! :D

**Comment by dysinger** [comment]
Switch from 4.06.1 to 4.07.x I get further but then:
```
#=== ERROR while compiling tls.0.10.2 =========================================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.07/.opam-switch/build/tls.0.10.2
# command              ~/.opam/4.07/bin/ocaml pkg/pkg.ml build --pinned false --tests false --with-lwt true --with-mirage true
# exit-code            1
# env-file             ~/.opam/log/tls-7-580b5c.env
# output-file          ~/.opam/log/tls-7-580b5c.out
### output ###
# [...]
# Error: Unbound value Nocrypto.Hash.hash_of_sexp
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'lib/tls.cmi' 'lib/tls.a' 'lib/tls.cmxs' 'lib/tls.cmxa'
#      'lib/tls.cma' 'lib/tls.cmx' 'lwt/tls-lwt.a' 'lwt/tls-lwt.cmxs'
#      'lwt/tls-lwt.cmxa' 'lwt/tls-lwt.cma' 'lwt/x509_lwt.cmx'
#      'lwt/x509_lwt.cmi' 'lwt/x509_lwt.mli' 'lwt/tls_lwt.cmx'
#      'lwt/tls_lwt.cmi' 'lwt/tls_lwt.mli' 'mirage/tls-mirage.a'
#      'mirage/tls-mirage.cmxs' 'mirage/tls-mirage.cmxa'
#      'mirage/tls-mirage.cma' 'mirage/tls_mirage.cmx' 'mirage/tls_mirage.cmi'
#      'mirage/tls_mirage.mli']: exited with 10
```

**Comment by dysinger** [comment]
A switch from 4.07 to 4.08 and it builds successfully. I have updated the P/R with the dockerfile (P/R #8)

**Comment by hannesm** [comment]
cool that it build successfully in the end! :) I promise to work on getting rid of the 44 opam packages in the overlay... rather sooner than later ;)

**Comment by hannesm** [comment]
@dysinger was your 4.07 issue output cached? i.e. if you re-run now, does it lead to the same result? (asking since i bumped / moved stuff around in the opam overlay)

**Comment by dysinger** [comment]
Note that the README.md says 4.07 currently (and it fails to build).  It fails at tls on 4.07. I accidentally deleted the output sorry.

**Comment by dysinger** [comment]
I will try 4.07 again now.

**Comment by dysinger** [comment]
I realized that the 4.07 compilation is above ("TLS")

**Comment by dysinger** [comment]
I am building 4.07 again from scratch now.

**Comment by dysinger** [comment]
4.07 works now.  I have updated the dockerfile with a variable for the OCAML version.  You can do this now.

```
for OCAML in 4.06 4.07 4.08 ; do docker build --build-arg=OCAML=${OCAML} --tag mirage-caldav:${OCAML} . ; done
```

**Comment by dysinger** [comment]
Works: 4.07 and 4.08. Broken <4.07

```
#=== ERROR while compiling mirage-conduit.3.2.0 ===============================#
# context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.06.1 | git+file:///home/opam/opam-repository
# path                 ~/.opam/4.06/.opam-switch/build/mirage-conduit.3.2.0
# command              ~/.opam/4.06/bin/dune build -p mirage-conduit -j 71
# exit-code            1
# env-file             ~/.opam/log/mirage-conduit-7-4f9ff0.env
# output-file          ~/.opam/log/mirage-conduit-7-4f9ff0.out
### output ###
# [...]
#        ocaml (internal)
# ocamlfind: Package `launchd.lwt' not found
# ocamlfind: Package `lwt_ssl' not found
# /home/opam/.opam/4.06/lib/tls
# Configuration
#   launchd: false
#   ssl    : false
#   tls    : true
# File "/home/opam/.opam/4.06/lib/tls/META", line 1, characters 0-0:
# Error: Library "tls-mirage" not found.
# -> required by library "tls.mirage" in /home/opam/.opam/4.06/lib/tls
# Hint: try: dune external-lib-deps --missing -j 71 -p mirage-conduit @@default
```

**Comment by dysinger** [comment]
I have built many times now with the opam overlay and it's working fine. I think this could be closed.
